### ISSUE TITLE
macOS High Sierra(版本：10.13.4)下无法运行

### ISSUE THREAD

**Issue by GanZhiXiong** [newpanjing/wenat-client-java#1]
用终端打开start.sh文件后，终端输出如下，但就是没有显示UI界面。
➜  ~ /Users/ganzhixiong/Downloads/wenat-client-1.0.3\ \(1\).zip\ Folder/start.sh ; exit;
start success.

[进程已完成]

**Comment by newpanjing** [comment]
从压缩文件中先解压呀，然后在运行撒
